server {
    listen 80;
    server_name _;

    root /var/www/public;   # в какой папке искать файлы сайта
    charset utf-8;

    gzip on;
    gzip_types application/json application/javascript text/css;

    location / {
        add_header Cache-Control "no-cache";
    }

    # в стандартном mime.types нет .otf
    location /assets/fonts/ {
        types { font/otf otf; }
        expires 1d;
    }

    # Все запросы /api/* обрабатывает единая точка входа PHP (код лежит вне public)
    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/src/api.php;
        fastcgi_pass php:9000;   # на какой порт кидать запрос fastcgi дальше
    }
}
